version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: dpin-uptime-db
    environment:
      POSTGRES_DB: dpin_uptime
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dpin_uptime"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
